### ISSUE TITLE
这个迁移能用吗  

### ISSUE THREAD

**Issue by DreamPWJ** [NervJS/taro-plugin-migrate#1]
从2版本到taro3自动迁移？

**Comment by DreamPWJ** [comment]
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
const migrateToVersion = cliVersion.split('.')[0];

**Comment by SyMind** [comment]
额，原来官方也准备了迁移工具了啊。
@DreamPWJ 你可以先用这个 https://github.com/SyMind/taro2-to-3
